
services:
  - type: web
    name: padelkey-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: SHOPIFY_SHOP_URL
        value: ${SHOPIFY_SHOP_URL}
      - key: SHOPIFY_API_KEY
        value: ${SHOPIFY_API_KEY}
    